// Code generated by MockGen. DO NOT EDIT.
// Source: ./prompt.go

// Package prompts is a generated GoMock package.
package prompts

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockPrompter is a mock of Prompter interface.
type MockPrompter struct {
	ctrl     *gomock.Controller
	recorder *MockPrompterMockRecorder
}

// MockPrompterMockRecorder is the mock recorder for MockPrompter.
type MockPrompterMockRecorder struct {
	mock *MockPrompter
}

// NewMockPrompter creates a new mock instance.
func NewMockPrompter(ctrl *gomock.Controller) *MockPrompter {
	mock := &MockPrompter{ctrl: ctrl}
	mock.recorder = &MockPrompterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPrompter) EXPECT() *MockPrompterMockRecorder {
	return m.recorder
}

// AskForSelectionFromList mocks base method.
func (m *MockPrompter) AskForSelectionFromList(direction string, listOptions []*ListOption) interface{} {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AskForSelectionFromList", direction, listOptions)
	ret0, _ := ret[0].(interface{})
	return ret0
}

// AskForSelectionFromList indicates an expected call of AskForSelectionFromList.
func (mr *MockPrompterMockRecorder) AskForSelectionFromList(direction, listOptions interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AskForSelectionFromList", reflect.TypeOf((*MockPrompter)(nil).AskForSelectionFromList), direction, listOptions)
}

// AskForString mocks base method.
func (m *MockPrompter) AskForString(direction string, validator StringValidator) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AskForString", direction, validator)
	ret0, _ := ret[0].(string)
	return ret0
}

// AskForString indicates an expected call of AskForString.
func (mr *MockPrompterMockRecorder) AskForString(direction, validator interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AskForString", reflect.TypeOf((*MockPrompter)(nil).AskForString), direction, validator)
}
