// Code generated by MockGen. DO NOT EDIT.
// Source: ./executor.go
//
// Generated by this command:
//
//	mockgen -source=./executor.go -destination=mockExecutor.go -package=executor --typed
//

// Package executor is a generated GoMock package.
package executor

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockExecutor is a mock of Executor interface.
type MockExecutor struct {
	ctrl     *gomock.Controller
	recorder *MockExecutorMockRecorder
	isgomock struct{}
}

// MockExecutorMockRecorder is the mock recorder for MockExecutor.
type MockExecutorMockRecorder struct {
	mock *MockExecutor
}

// NewMockExecutor creates a new mock instance.
func NewMockExecutor(ctrl *gomock.Controller) *MockExecutor {
	mock := &MockExecutor{ctrl: ctrl}
	mock.recorder = &MockExecutorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockExecutor) EXPECT() *MockExecutorMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockExecutor) Execute(ctx context.Context, requirements Requirements) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, requirements)
	ret0, _ := ret[0].(error)
	return ret0
}

// Execute indicates an expected call of Execute.
func (mr *MockExecutorMockRecorder) Execute(ctx, requirements any) *MockExecutorExecuteCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockExecutor)(nil).Execute), ctx, requirements)
	return &MockExecutorExecuteCall{Call: call}
}

// MockExecutorExecuteCall wrap *gomock.Call
type MockExecutorExecuteCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockExecutorExecuteCall) Return(arg0 error) *MockExecutorExecuteCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockExecutorExecuteCall) Do(f func(context.Context, Requirements) error) *MockExecutorExecuteCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockExecutorExecuteCall) DoAndReturn(f func(context.Context, Requirements) error) *MockExecutorExecuteCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
