// Code generated by MockGen. DO NOT EDIT.
// Source: ./checker.go
//
// Generated by this command:
//
//	mockgen -source=./checker.go -destination=mockChecker.go -package=langs --typed
//

// Package langs is a generated GoMock package.
package langs

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockChecker is a mock of Checker interface.
type MockChecker struct {
	ctrl     *gomock.Controller
	recorder *MockCheckerMockRecorder
	isgomock struct{}
}

// MockCheckerMockRecorder is the mock recorder for MockChecker.
type MockCheckerMockRecorder struct {
	mock *MockChecker
}

// NewMockChecker creates a new mock instance.
func NewMockChecker(ctrl *gomock.Controller) *MockChecker {
	mock := &MockChecker{ctrl: ctrl}
	mock.recorder = &MockCheckerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockChecker) EXPECT() *MockCheckerMockRecorder {
	return m.recorder
}

// CheckDependency mocks base method.
func (m *MockChecker) CheckDependency(dependency any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckDependency", dependency)
	ret0, _ := ret[0].(error)
	return ret0
}

// CheckDependency indicates an expected call of CheckDependency.
func (mr *MockCheckerMockRecorder) CheckDependency(dependency any) *MockCheckerCheckDependencyCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckDependency", reflect.TypeOf((*MockChecker)(nil).CheckDependency), dependency)
	return &MockCheckerCheckDependencyCall{Call: call}
}

// MockCheckerCheckDependencyCall wrap *gomock.Call
type MockCheckerCheckDependencyCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockCheckerCheckDependencyCall) Return(arg0 error) *MockCheckerCheckDependencyCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockCheckerCheckDependencyCall) Do(f func(any) error) *MockCheckerCheckDependencyCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockCheckerCheckDependencyCall) DoAndReturn(f func(any) error) *MockCheckerCheckDependencyCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// CheckSetup mocks base method.
func (m *MockChecker) CheckSetup() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckSetup")
	ret0, _ := ret[0].(error)
	return ret0
}

// CheckSetup indicates an expected call of CheckSetup.
func (mr *MockCheckerMockRecorder) CheckSetup() *MockCheckerCheckSetupCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckSetup", reflect.TypeOf((*MockChecker)(nil).CheckSetup))
	return &MockCheckerCheckSetupCall{Call: call}
}

// MockCheckerCheckSetupCall wrap *gomock.Call
type MockCheckerCheckSetupCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockCheckerCheckSetupCall) Return(arg0 error) *MockCheckerCheckSetupCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockCheckerCheckSetupCall) Do(f func() error) *MockCheckerCheckSetupCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockCheckerCheckSetupCall) DoAndReturn(f func() error) *MockCheckerCheckSetupCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// CleanUp mocks base method.
func (m *MockChecker) CleanUp() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CleanUp")
	ret0, _ := ret[0].(error)
	return ret0
}

// CleanUp indicates an expected call of CleanUp.
func (mr *MockCheckerMockRecorder) CleanUp() *MockCheckerCleanUpCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CleanUp", reflect.TypeOf((*MockChecker)(nil).CleanUp))
	return &MockCheckerCleanUpCall{Call: call}
}

// MockCheckerCleanUpCall wrap *gomock.Call
type MockCheckerCleanUpCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockCheckerCleanUpCall) Return(arg0 error) *MockCheckerCleanUpCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockCheckerCleanUpCall) Do(f func() error) *MockCheckerCleanUpCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockCheckerCleanUpCall) DoAndReturn(f func() error) *MockCheckerCleanUpCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetDependency mocks base method.
func (m *MockChecker) GetDependency(dependency any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDependency", dependency)
	ret0, _ := ret[0].(error)
	return ret0
}

// GetDependency indicates an expected call of GetDependency.
func (mr *MockCheckerMockRecorder) GetDependency(dependency any) *MockCheckerGetDependencyCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDependency", reflect.TypeOf((*MockChecker)(nil).GetDependency), dependency)
	return &MockCheckerGetDependencyCall{Call: call}
}

// MockCheckerGetDependencyCall wrap *gomock.Call
type MockCheckerGetDependencyCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockCheckerGetDependencyCall) Return(arg0 error) *MockCheckerGetDependencyCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockCheckerGetDependencyCall) Do(f func(any) error) *MockCheckerGetDependencyCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockCheckerGetDependencyCall) DoAndReturn(f func(any) error) *MockCheckerGetDependencyCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Setup mocks base method.
func (m *MockChecker) Setup() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Setup")
	ret0, _ := ret[0].(error)
	return ret0
}

// Setup indicates an expected call of Setup.
func (mr *MockCheckerMockRecorder) Setup() *MockCheckerSetupCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Setup", reflect.TypeOf((*MockChecker)(nil).Setup))
	return &MockCheckerSetupCall{Call: call}
}

// MockCheckerSetupCall wrap *gomock.Call
type MockCheckerSetupCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockCheckerSetupCall) Return(arg0 error) *MockCheckerSetupCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockCheckerSetupCall) Do(f func() error) *MockCheckerSetupCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockCheckerSetupCall) DoAndReturn(f func() error) *MockCheckerSetupCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
