// Code generated by MockGen. DO NOT EDIT.
// Source: ./config.go

// Package config is a generated GoMock package.
package config

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockConfigManager is a mock of ConfigManager interface.
type MockConfigManager struct {
	ctrl     *gomock.Controller
	recorder *MockConfigManagerMockRecorder
}

// MockConfigManagerMockRecorder is the mock recorder for MockConfigManager.
type MockConfigManagerMockRecorder struct {
	mock *MockConfigManager
}

// NewMockConfigManager creates a new mock instance.
func NewMockConfigManager(ctrl *gomock.Controller) *MockConfigManager {
	mock := &MockConfigManager{ctrl: ctrl}
	mock.recorder = &MockConfigManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConfigManager) EXPECT() *MockConfigManagerMockRecorder {
	return m.recorder
}

// GetDefaultPath mocks base method.
func (m *MockConfigManager) GetDefaultPath() (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDefaultPath")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDefaultPath indicates an expected call of GetDefaultPath.
func (mr *MockConfigManagerMockRecorder) GetDefaultPath() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDefaultPath", reflect.TypeOf((*MockConfigManager)(nil).GetDefaultPath))
}

// SetValueOf mocks base method.
func (m *MockConfigManager) SetValueOf(key, value string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetValueOf", key, value)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetValueOf indicates an expected call of SetValueOf.
func (mr *MockConfigManagerMockRecorder) SetValueOf(key, value interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetValueOf", reflect.TypeOf((*MockConfigManager)(nil).SetValueOf), key, value)
}

// UnsetValuesOf mocks base method.
func (m *MockConfigManager) UnsetValuesOf(key string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnsetValuesOf", key)
	ret0, _ := ret[0].(error)
	return ret0
}

// UnsetValuesOf indicates an expected call of UnsetValuesOf.
func (mr *MockConfigManagerMockRecorder) UnsetValuesOf(key interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnsetValuesOf", reflect.TypeOf((*MockConfigManager)(nil).UnsetValuesOf), key)
}
