// Code generated by MockGen. DO NOT EDIT.
// Source: ./compressor.go

// Package compressor is a generated GoMock package.
package compressor

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockCompressor is a mock of Compressor interface.
type MockCompressor struct {
	ctrl     *gomock.Controller
	recorder *MockCompressorMockRecorder
}

// MockCompressorMockRecorder is the mock recorder for MockCompressor.
type MockCompressorMockRecorder struct {
	mock *MockCompressor
}

// NewMockCompressor creates a new mock instance.
func NewMockCompressor(ctrl *gomock.Controller) *MockCompressor {
	mock := &MockCompressor{ctrl: ctrl}
	mock.recorder = &MockCompressorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCompressor) EXPECT() *MockCompressorMockRecorder {
	return m.recorder
}

// CompressDirectory mocks base method.
func (m *MockCompressor) CompressDirectory(source, target string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CompressDirectory", source, target)
	ret0, _ := ret[0].(error)
	return ret0
}

// CompressDirectory indicates an expected call of CompressDirectory.
func (mr *MockCompressorMockRecorder) CompressDirectory(source, target interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CompressDirectory", reflect.TypeOf((*MockCompressor)(nil).CompressDirectory), source, target)
}

// UncompressFromUrl mocks base method.
func (m *MockCompressor) UncompressFromUrl(url string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UncompressFromUrl", url)
	ret0, _ := ret[0].(error)
	return ret0
}

// UncompressFromUrl indicates an expected call of UncompressFromUrl.
func (mr *MockCompressorMockRecorder) UncompressFromUrl(url interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UncompressFromUrl", reflect.TypeOf((*MockCompressor)(nil).UncompressFromUrl), url)
}
